### ISSUE TITLE
[Bug]: Cannot create more than one un-named secret for an object

### ISSUE THREAD

**Issue by j-oss2023** [Onemind-Services-LLC/netbox-secrets#100]
### NetBox Secrets plugin version

v1.9.0

### NetBox version

v3.6.1

### Steps to Reproduce

**First secret created just fine,**

![image](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/144011572/08bcce71-635a-48fc-811a-f43f542a3830)

![image](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/144011572/6b72f26f-b0ae-43e6-94fc-efcacfe96cae)

**Second attempt**
![image](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/144011572/91938ee4-6bee-4955-9959-0418b5e4fa17)
![image](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/144011572/1b4bdfc2-c3ca-4588-969f-680c822938fe)

Looks like it isn't constrained by uuid but rather name, when you create a second un-named secret on an object you get this error, 

Solution: unique names 

Great plugin !
### Expected Behavior

Create multiple un-named secrets

### Observed Behavior

![image](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/144011572/1b4bdfc2-c3ca-4588-969f-680c822938fe)

**Comment by abhi1693** [comment]
Thank you for opening a bug report. Unfortunately, the information you have provided is not sufficient for someone else to attempt to reproduce the reported behavior. Remember, each bug report must include detailed steps that someone else can follow on a clean, empty NetBox installation to reproduce the exact problem you're experiencing. These instructions should include the creation of any involved objects, any configuration changes, and a complete accounting of the actions being taken. Also be sure that your report does not reference data on the public NetBox demo, as that is subject to change at any time by an outside party and cannot be relied upon for bug reports.

> Without it, it errored out loading secrets.js

You need to run `python manage.py migrate` from your virtual environment. This is not a bug. Please see the installation steps: https://github.com/Onemind-Services-LLC/netbox-secrets?tab=readme-ov-file#installation

**Comment by abhi1693** [comment]
I'm sorry but the title is not enough for us to reproduce the issue. Ping me when you have provided more details as I have asked in the last comment and we can take a look.

**Comment by j-oss2023** [comment]
Check i've updated the original post,

If you create one secret with no name, that works,
if you try and create another secret with no name, it fails with screenshot

**Comment by abhi1693** [comment]
We may have to tweak this line to allow secrets to be unique when the name is not empty and keep the current implementation

https://github.com/Onemind-Services-LLC/netbox-secrets/blob/d9fbd964e1af1653ccaf6702cb03a6f9a9fa3e73/netbox_secrets/models/secrets.py#L281-L281

**Comment by j-oss2023** [comment]
"when the name is empty" you mean... 

great plugin, but now i've got you - wondering if you could point me in the right direction for API use,

I have just stored all my secrets and now i'm wondering how to retrieve them from a remote system, I've got the user key stored

**Comment by j-oss2023** [comment]
ignore that last comment, just found the doc! 

THANKS !

**Comment by yash-pal1** [comment]
![Screenshot from 2024-03-07 17-59-09](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/141638359/ccc8094e-42be-463f-afd8-7d025c303890)

we can create multiple un-named objects with different roles.
