### ISSUE TITLE
[Bug]: Button copy to clipboard not working

### ISSUE THREAD

**Issue by rmuehl** [Onemind-Services-LLC/netbox-secrets#104]
### NetBox Secrets plugin version

1.8.5

### NetBox version

3.5.9

### Steps to Reproduce

Unlock secret and then click Copy to clipboard. Bot the clipboard is empty.

### Expected Behavior

Secret gets copied to the clipboard.

### Observed Behavior

The event handler is missing:
![image](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/22004345/e779d09f-2842-4320-a900-815ef832265c)

**Comment by abhi1693** [comment]
I have opened an FR to allow to fix the implementation so I'm marking this as blocked until the upstream issue is resolved first in a release.

**Comment by uedvt359** [comment]
@abhi1693, it looks like this landed in upstream
