### ISSUE TITLE
[Bug]: Unable to Activate Selected User Keys in Admin Panel

### ISSUE THREAD

**Issue by agusadjadj** [Onemind-Services-LLC/netbox-secrets#106]
### NetBox Secrets plugin version

v1.9.0

### NetBox version

v3.6.4

### Steps to Reproduce

- The user creates a user key.
- The user recieves the " Status: Your user key is inactive. Ask an administrator to enable it for you."
- Enter with admin. Select the user to activate in (old) Admin Panel.
- After check the box, Select the "Activate selected user" error raises.
![Captura desde 2023-11-02 10-13-47](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/32807381/8f833f34-d057-4b78-aaaf-cd65d3f63237)

### Expected Behavior

The user is active after the "Activate selected user" and Go button ocurrs

### Observed Behavior

Field 'id' expected a number but got ''. Seems like the checkbox has a missfunctionality

**Comment by cjwagz** [comment]
Receiving the same error on Plugin 1.9.0 and Netbox 3.6.4

**Comment by jonnycastaway** [comment]
Hello,
having the same issue with Netbox Version 3.6.5 and Plugin Version 1.9.0
Is there any workaround? It's a real showstopper.

**Comment by abhi1693** [comment]
I have looked into this a bit more and seems like no model on the admin side can perform bulk operations in NetBox. I'm still trying to find if this has anything to do with how NetBox is structured or an internal Django bug.

**Comment by abhi1693** [comment]
The issue is caused due to https://github.com/netbox-community/netbox/compare/v3.6.3...v3.6.4#diff-310332579486e53e626dd095399f64c29fc215b386672af995b764f78328d27eR435

**Comment by jonnycastaway** [comment]
> The issue is caused due to [netbox-community/netbox@v3.6.3...v3.6.4#diff-310332579486e53e626dd095399f64c29fc215b386672af995b764f78328d27eR435](https://github.com/netbox-community/netbox/compare/v3.6.3...v3.6.4#diff-310332579486e53e626dd095399f64c29fc215b386672af995b764f78328d27eR435)
> 
> ```
> <input type="hidden" name="{{ widget.name }}" value="">
> ```
> 
> Either [netbox-community/netbox#13963](https://github.com/netbox-community/netbox/pull/13963) needs to revert or we need to figure out a way around it

Good finding. Hopefully they merge fast.
