### ISSUE TITLE
Mismatch in PluginConfig Attributes and Update descriptions in setup.py file

### ISSUE THREAD

**Issue by yash-pal1** [Onemind-Services-LLC/netbox-secrets#124]
### NetBox Version

v3.5.9

### NetBox Plugin Version

v1.10.1

### Steps to Reproduce

The current implementation of the `PluginConfig` class in the `__init__.py` file shows a mismatch between the defined attributes (`verbose_name` and `description`).

### Expected Behavior

Specifically, the following corrections should be made in the `__init__.py` file:
* `verbose_name = metadata.get("Name")`
* `description = metadata.get("Summary")`

## *Additional Context:*

* Also update the description and  dynamically updating the long description in the `setup.py` file.

### Example for Setup.py

```
import os

# ...

# Set long description from README.md
readme = os.path.join(os.path.dirname(__file__), 'README.md')
with open(readme) as fh:
    long_description = fh.read()

# ...

setup(
    description=`'Plugin Description'`,
    long_description=long_description,
    long_description_content_type="text/markdown",
)
```

* Note: Replace `Plugin Description` with the actual description of your plugin.

### Observed Behavior

The observed behaviour indicates that these attributes are being set as follows:
`verbose_name = metadata.get("Summary")`
`description = metadata.get("Long-Description")`

### Resolve By

2021-01-04

**Comment by kprince28** [comment]
The reported issue has been successfully resolved with the following commit:: https://github.com/Onemind-Services-LLC/netbox-secrets/commit/611083e5876c07761f2770447a1d1f8787c77fff

This issue is being closed.
