### ISSUE TITLE
[Feature]:  Hashicorp Vault integration?

### ISSUE THREAD

**Issue by miconx** [Onemind-Services-LLC/netbox-secrets#125]
### NetBox version

v3.6.0

### Feature type

Add a function

### Proposed functionality

is there a way to integrate this plugin with an external secret store like hashicorp vault?

### Use case

store & sync secrets with external / central store

**Comment by abhi1693** [comment]
Currently this is not possible. However you are welcome to provide a detailed implementation of how you think this should be implemented
