### ISSUE TITLE
[Docs]: Add help for upgrading from netbox 2.11 to 3.x

### ISSUE THREAD

**Issue by rkearsley** [Onemind-Services-LLC/netbox-secrets#134]
### Change Type

Addition

### Area

Installation instructions

### Proposed Changes

When upgrading from 2.11.x to netbox 3.x, please document what happens to the existing secrets already stored in 2.11.x
- Will the existing secrets be lost and have to be recreated in 3.x?
- Or will netbox-secrets bring the 2.11.x secrets forward?
- Or does the (also defunct) DanSheps/netbox-secretstore plugin need to be used first as a migration step?

many thanks

**Comment by abhi1693** [comment]
This plugin only supports v3+. So, maybe you should use the secretstore plugin as an intermediary for the migration.
