### ISSUE TITLE
Netbox 4.0 Support

### ISSUE THREAD

**Issue by uedvt359** [Onemind-Services-LLC/netbox-secrets#136]
### Proposed Changes

Netbox 4.0 has been released: https://github.com/netbox-community/netbox/releases/tag/v4.0.0

### Justification

seems to need quite a few changes: https://docs.netbox.dev/en/feature/plugins/development/migration-v4/

**Comment by olivierlambert** [comment]
:+1: here, that would be nice to have it compatible with 4.0!

**Comment by Songxwn** [comment]
we need to

**Comment by olivierlambert** [comment]
Is there anything we can do to help?

**Comment by rmuehl** [comment]
desperately need this too...

**Comment by olivierlambert** [comment]
@abhi1693 since it seems you are the most active contributor, could you tell us if there's anything we can do to help on this?

**Comment by abhi1693** [comment]
We are facing some issues with the migrations and changelog of the plugin as we are trying to move it from admin to netbox view. Our team is working on this and should have something soon

**Comment by olivierlambert** [comment]
Thank you very much @abhi1693 !

**Comment by salvador-andes** [comment]
Thank you @abhi1693, we are all looking for v4.0 compatibility :)

**Comment by abhi1693** [comment]
@salvador-andes @olivierlambert @rmuehl @Songxwn @uedvt359 

The v4 changes are nearly completed. We like to get some feedback on the changes before we merge the PR. THere are still minor changes left but the majority of changes are now completed.

**Comment by mraerino** [comment]
is it possible to release a pre-release / RC from the branch with the changes?

**Comment by lill-peter** [comment]
Hello! 
I really appreciate your plugin
New version of Netbox 4.1 and the plugin can not be installed.
Cheers
