### ISSUE TITLE
[Bug]: error deleting users

### ISSUE THREAD

**Issue by KennethFoliWork** [Onemind-Services-LLC/netbox-secrets#151]
### NetBox Secrets plugin version

v2.0.3

### NetBox version

4.0.8

### Steps to Reproduce

i am going to admin -> users and selecting a user and select delete

### Expected Behavior

that the user was removed

### Observed Behavior

then i am trying to delete a user i am getting this error

<class 'django.db.utils.IntegrityError'>

update or delete on table "users_user" violates foreign key constraint "secrets_userkey_user_id_13ada46b_fk_auth_user_id" on table "netbox_secretstore_userkey"
DETAIL:  Key (id)=(3) is still referenced from table "netbox_secretstore_userkey".

Python version: 3.10.12
NetBox version: 4.0.8
Plugins: 
  netbox_secrets: 2.0.3

**Comment by abhi1693** [comment]
This is a bug from the [netbox secret store](https://github.com/DanSheps/netbox-secretstore) plugin.
