### ISSUE TITLE
[maintenance]: NetBox Community v4.1.0

### ISSUE THREAD

**Issue by lill-peter** [Onemind-Services-LLC/netbox-secrets#159]
### Proposed Changes

Hello!
I really appreciate your plugin
New version of Netbox 4.1 and the plugin (v2.0.3) can not be installed.
Cheers

### Justification

-

**Comment by parkerschoenig** [comment]
@abhi1693 I see you fixed the issue for v4.0. Anything we can do to assist for v4.1 support? Thanks!

**Comment by abhi1693** [comment]
Fixed in https://github.com/Onemind-Services-LLC/netbox-secrets/pull/161
