### ISSUE TITLE
[Feature]: Enable usage of session key list and secrets list endpoints using pynetbox

### ISSUE THREAD

**Issue by FontouraAbreu** [Onemind-Services-LLC/netbox-secrets#172]
### NetBox version

Community v.4.1.4

### Feature type

Add a function

### Proposed functionality

Add a way to send the Private Key and session key in Pynetbox's `api()` method.

### Use case

Using the `pynetbox` lib we're not able to insert the Private Key needed to retrieve the user's session key.
The same goes to retrieving secrets from netbox.

**Comment by FontouraAbreu** [comment]
Maybe this would be a `Pynetbox` feature. I'm not sure if there's a way to make a kinda of wrapper to deal with this.

**Comment by abhi1693** [comment]
The plugin is fully compatible with pynetbox. Maybe you are doing something incorrectly which is causing issues

**Comment by FontouraAbreu** [comment]
Doesn't it have a docs example on how to use it with pynetbox?

**Comment by FontouraAbreu** [comment]
just found this [issue](https://github.com/netbox-community/netbox/discussions/13409) where you've put and example
