### ISSUE TITLE
[Docs]: Add section of why this plugin was created and what is it trying to solve

### ISSUE THREAD

**Issue by dmulyalin** [Onemind-Services-LLC/netbox-secrets#25]
### Change Type

Addition

### Area

Other

### Proposed Changes

Hello,

IMHO it would be good to have an overview section in readme file describing why this plugin was created and what it tries to solve. Highlighting key advantages and differences in comparison with netbox_secretstore plugin also might be useful.

**Comment by abhi1693** [comment]
That's a good suggestion. I'll work up something this week and add to the documentation.
