### ISSUE TITLE
[Feature]: Add ability to link the device with secrets to click and connect

### ISSUE THREAD

**Issue by PVM-NL** [Onemind-Services-LLC/netbox-secrets#33]
### NetBox version

v3.4.3

### Feature type

Add a function

### Proposed functionality

Is it an option to directly use the combination of secrets and device to link to each other. 
Which then provide the connection straight to device by clicking on it by using ssh / rdp as protocol option.
So that it will be a one click option as in the form of connect button with the secrets.
![image](https://user-images.githubusercontent.com/120473446/215693348-da7a3294-6ecc-4a0a-9ad1-57648c6d5234.png)
Just a mockup i can imagine that you would say the device role can be the type/name credentials and just add the button and maybe the protocol if needed.

### Use case

Just a nice to have that you can immediatly click and check the device.

### External dependencies

Dont know

**Comment by abhi1693** [comment]
This may be possible to with the current implementation. Could you please specify all the protocols that you think should be provided for selection with the browser handler formats?

**Comment by PVM-NL** [comment]
Aah thats a good one. I think the most important one are mostly used:
- SSH
- RDP

**Extra:**
- HTTP
- HTTPS
- TELNET
- VNC

**Comment by abhi1693** [comment]
And how should the IP and port be used for generating the link? Should we use the primary IP but which port? Because it makes most sense to me to utilize the services on the device, however, this seems to require more details in order to implement for the use case.

**Comment by PVM-NL** [comment]
yes i think the primary IP from the device where the secret is linked would be the right one. When selecting the type you know mostly the default port but could be someone set a different port on the protocol. (SSH 22, RDP 3389, VNC 5900, TELNET 23)

But someone could ofcourse change the port. Perhaps the option in secrets to specify the protocol with port and then use that in the connection.

**Comment by abhi1693** [comment]
I'll discuss this internally and see if this is a viable solution

**Comment by abhi1693** [comment]
After a lot of thought, I think this should be made doable using custom links. I'd like to keep the current scope of the plugin contained to secrets. That being said, I'll see what options are available to make this work in the template using the links

**Comment by PVM-NL** [comment]
Awesome i will look forward to if you might find something.

As custom links might be usefull so people can create there own connection string like we use on linux/mac

ssh username:password@hostname.

**Comment by abhi1693** [comment]
I'm going to close this as there hasn't been much activity on this.
