### ISSUE TITLE
[Bug]: Unable to generate session key via API

### ISSUE THREAD

**Issue by kirk444** [Onemind-Services-LLC/netbox-secrets#47]
### NetBox Secrets plugin version

1.7.6

### NetBox version

3.4.7

### Steps to Reproduce

I recently migrated from netbox-secretstore (1.4.4) to netbox-secrets (1.7.6), while updating tools to new API path I found I am unable to generate session keys. This same token and key worked fine with secretstore, and works for other API calls now, so I am confident they are correct and valid.

curl -X POST \
-H "Authorization: Token <vaild token>" \
-H "Accept: application/json; indent=4" \
--data-urlencode "private_key@/path/to/netbox/key" \
https://netbox/api/plugins/secrets/get-session-key/

### Expected Behavior

json object with session key is returned

### Observed Behavior

{
    "detail": "Unsupported media type \"application/x-www-form-urlencoded\" in request."
}

**Comment by abhi1693** [comment]
Does it work via the UI?

**Comment by kirk444** [comment]
Yes, I am able to unlock secrets normally via the regular UI (e.g. visit the device page, click the unlock next to a secret, provide/paste private key).

**Comment by kirk444** [comment]
Has anyone successfully used the REST API to retrieve a session key? If so, how are you sending the private_key? It seems that the instructions are telling me to use "--data-urlencode" but the API endpoint is stating that url encoded data is not accepted.

**Comment by kirk444** [comment]
I believe this issue is related to https://github.com/netbox-community/netbox/issues/10031.

I've found that if I modify netbox/netbox/settings.py and add " 'rest_framework.parsers.FormParser'," back to the "DEFAULT_PARSER_CLASSES" that normal functionality is restored.

I know this worked previously with netbox-secretstore, though, so I wonder if something was specifically being done to add that parser there?

**Comment by kirk444** [comment]
The reason the old plugin worked is that they override the DEFAULT_PARSER_CLASSES in the view for the session keys, I added a PR to duplicate that behavior here.

**Comment by uedvt359** [comment]
I was able to use the endpoint by adding `rest_framework.parsers.FormParser` to `DEFAULT_PARSER_CLASSES`, but I'm not happy with this workaround.

I tried applying https://github.com/DanSheps/netbox-secretstore/pull/92/files, but that didn't help.

**Comment by kirk444** [comment]
@uedvt359 thanks, yes, you're absolutely right, I'll update that now

**Comment by robertlynch3** [comment]
I have no idea if its related, but I keep getting
```json
{
    "detail": "Method \"POST\" not allowed."
}
```

I am running the curl statement just as its described 
```
curl -X 'POST' https://{fqdn}/api/plugins/secrets/secrets/get-session-key/ \
-H "Authorization: Token {token}" \
-H "Accept: application/json; indent=4" \
--data-urlencode "private_key@/{pwd}"
```

**Comment by abhi1693** [comment]
I think it would be bes to update the docs to reflect how to call the endpoint using the JSON payload instead. Unless, there is some real value in adding the parsers that I'm not seeing at the moment.

**Comment by kirk444** [comment]
If that's what you prefer, that's perfectly fine with me, I don't know how to do that though. My objective here was pretty limited to getting the basic functionality of retrieving a session key back to working the way it did under netbox_secretstore. If you can help me understand how to use the JSON payload to retrieve the session key, then I'd be happy to help update the documentation.

**Comment by uedvt359** [comment]
> I think it would be best to update the docs to reflect how to call the endpoint using the JSON payload instead. Unless, there is some real value in adding the parsers that I'm not seeing at the moment.

I'd appreciate it if the behavior of the previous plugin was restored. We have a lot of code that uses that way of accessing session keys.

**Comment by abhi1693** [comment]
In future we will only support json payloads. However to keep backward compatibility for old plugin users we will accept the solution for now
