### ISSUE TITLE
[Bug]: Dont work after update netbox to 3.5.0

### ISSUE THREAD

**Issue by SerhiiZahuba** [Onemind-Services-LLC/netbox-secrets#53]
### NetBox Secrets plugin version

1.7.6

### NetBox version

3.5.0

### Steps to Reproduce

update netbox to v 3.5.0 and after 
python3 netbox/manage.py migrate

i see

_django.core.exceptions.ImproperlyConfigured: Plugin netbox_secrets requires NetBox maximum version 3.4.99._

### Expected Behavior

without errors

### Observed Behavior

django.core.exceptions.ImproperlyConfigured: Plugin netbox_secrets requires NetBox maximum version 3.4.99

**Comment by abhi1693** [comment]
Please see this https://github.com/Onemind-Services-LLC/netbox-secrets#compatibility

We are not yet ready for v3.5.0. As it was released just a few hours ago, it'll take a atleast 1 week before we can roll out an update as we may need to update code to be compliant.

You are welcome to do so if you wish to help us fastrack the work.

**Comment by mraerino** [comment]
is this going to be released soon?

**Comment by abhi1693** [comment]
Yes, it is scheduled for either today or latest by tomorrow. We are working on the last PR that is pending to be merged.
