### ISSUE TITLE
[Feature]: Add the possibility of permissions to different groups/users keys as appropriate

### ISSUE THREAD

**Issue by agusadjadj** [Onemind-Services-LLC/netbox-secrets#62]
### NetBox version

v3.5.1

### Feature type

Add a function

### Proposed functionality

Depending on the type of secret role (Ex: Admin Password / Guest Password / Other Password), give users permission to see the passwords.

### Use case

The engineering area that manages the administration users should not have access to the users that the electrical area manages. Each user/group should have a certain amount of permissions to access the password groups.

**Comment by abhi1693** [comment]
You should be able to achieve this using permission constraints. Is there anything more specific that is needed here?

**Comment by agusadjadj** [comment]
First of all, thanks for the prompt response. In principle, nothing more specific than what was previously described.

I was trying to understand how constraints work in this plugin and in general. I had no success looking for some documentation particularly for this plugin, could you give me an example, or something to be able to configure the constraint correctly?
If there is also a document where to find the objects that can be specified as constraints, since I could not find it and, as I said before, I have never worked with this functionality.

Thanks a lot

**Comment by abhi1693** [comment]
Here is a simple one. In your permission, choose the object type `SecretRole` and in constraints add

```
{"role__slug": "admin-password"}
```

And, then assign this to either users or groups. This one means that those with the permission are allowed on role with slug `admin-password`. You can similar create more complex constraints on your needs.

**Comment by agusadjadj** [comment]
Hey.
I don't know why I get the following error when I try to add the line of code you provided.

`Invalid filter for <class 'netbox_secrets.models.secrets.SecretRole'>: Cannot resolve keyword 'role' into field. Choices are: comments, created, custom_field_data, description, id, journal_entries, last_updated, name, secrets, slug, tagged_items, tags`

I've been trying other combinations, but none of them suit what I really need: That I can see only the secrets that belong to a group. In the meantime, I will continue trying until, I hope, I reach a solution, or wait for your response.

If I test only with ID, it filters both the secrets and the groups. If I try role__id, same error as above.
