### ISSUE TITLE
[Bug]: Adding Secrets is not appearing 

### ISSUE THREAD

**Issue by orenr2301** [Onemind-Services-LLC/netbox-secrets#77]
### NetBox Secrets plugin version

v1.8.3

### NetBox version

v3.5.3

### Steps to Reproduce

Netbox is installed as Netbox docker 
This means installed via Docker-Compose 

In case you are doing it manually as described in the readme file you will to:

1. you need to get inside the netbox-docker-netbox-1 container 
2. followup the commands described in the readme file of how to install the netbox-secrets  plugin

 
Follow up on this manual guide on how to make an image with plugins 
https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins

I have followed this guide and was able to add additional plugins as well 
Now in the plugins section at NETBOX SECRET 

 
![image](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/117763723/b5230590-ca29-49f8-8af7-173cf2ad5e7a)

When clicking on Secrets - im not have any button to add a secret or import a secret - I can only create a role and user-key

 
Please any ideas - as I have dig al the file structure to understand if I am missing a functionality that i need to enable but couldn't find - So I'm calling it a BUG, 

unless I'm doing one of the plugin installation steps wrong, and if i do, than i would be more than happy to know where im wrong and what i need to do 

### Expected Behavior

Expecting to have at least a button for creating secrets when im on the secret panel view

![image](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/117763723/2e026121-59b5-4ea6-bfc9-5cb5822f24e4)

### Observed Behavior

where is the way to add secret ?? 

![image](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/117763723/ea269eca-1148-4c61-b7df-23f8ad7b28c8)

**Comment by abhi1693** [comment]
Secrets can only be added be added via the model that you have enabled them for. Example, the defaults are device and virtual machine, so you will have to go to the specific object page, and click on the add secret button depending on how you have displayde your panel, weather its a object panel or a tab.
