### ISSUE TITLE
[Feature]: Add clone button for secret object view

### ISSUE THREAD

**Issue by abhi1693** [Onemind-Services-LLC/netbox-secrets#78]
### NetBox version

v3.5.4

### Feature type

Add a function

### Proposed functionality

Add a clone button to the secret object view. This should clone the assinged object, role and tags

### Use case

I want to quickly add several secrets to the same object with the same role and tags.

**Comment by kprince28** [comment]
@abhi1693 This feature is already implemented in v1.8.x or later. You can check with v1.8.x and close this issue.
