### ISSUE TITLE
[Bug]: Unable to view secrets in netbox web ui (3.5.4 / 1.8.3 + 1.8.5)

### ISSUE THREAD

**Issue by kirk444** [Onemind-Services-LLC/netbox-secrets#81]
### NetBox Secrets plugin version

v1.8.3 / v1.8.5

### NetBox version

v3.5.4

### Steps to Reproduce

Upgraded netbox from 3.4.10 to 3.5.4. Upgrade completed normally. Indicated version of netbox-secrets is v1.8.3. I've manually installed from the downloaded v1.8.5 release as well, but that still indicates v1.8.3 and appears to have the same issue.

After upgrade, attempting to a view a secret via the web UI fails.

After clicking "unlock secret" the "Enter Private RSA Key" prompt is shown, and the correct key is accepted (green toaster popup: " Session Key Received / You may now unlock secrets."). The secret is not revealed. Clicking the "unlock secrets" button again triggers another prompt for entering the private key.

As far as I can tell, API access to keys is working normally outside the netbox web interface.

### Expected Behavior

I expect the secret to be shown after the correct private key is provided.

### Observed Behavior

The secret is never shown, and the "enter private rsa key" dialog is shown repeatedly.

**Comment by abhi1693** [comment]
Make sure you have properly run `collectstatic` command and cleared the browser cache including the cookies. This seems like your static files aren't updated and are still referencing the old one from v3.4.10.

You can also use `collectstatic --clear` to ensure old files are removed first before collecting the new ones.

**Comment by kirk444** [comment]
Clearing and repopulating the static files had no effect, the behavior was the same. Clearing the browser cache has resolved the issue.
