### ISSUE TITLE
[Bug]: Cannot decrypt existing secrets once the RSA key pair has been changed

### ISSUE THREAD

**Issue by hlloreda** [Onemind-Services-LLC/netbox-secrets#88]
### NetBox Secrets plugin version

1.7.6

### NetBox version

3.4.10

### Steps to Reproduce

1. Create a first secret using one RSA key pair
2. Change the user's RSA key pair to another key pair
3. Try to decrypt the first secret
4. Reswitch to the initial RSA key pair
5. Try to decrypt the first secret

The steps can be seen [here](https://drive.google.com/file/d/1FsrkeI7pOm1Ul6FHr_I7AR7RXUhC_S_C/view)

### Expected Behavior

For step 3, a popup saying that this secret has been encrypted with another key.
For step 5, the decrypted secret

### Observed Behavior

`Can't decode byte` error

**Comment by abhi1693** [comment]
The reported issue is not a bug as the form clearly states that once a key is changed another administrator activate it. Your steps do not include that this was done.

**Comment by abhi1693** [comment]
I saw the video and the issue is that re-saving the form marked the key as active which should not have happened. In any case, a new bug should be filed to fix this issue as the one reported is incorrect.
